/** Synthetic, populated native-IPC fixtures for visual inspection; never platform acceptance evidence. */
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
const root=fileURLToPath(new URL('../',import.meta.url)).replace(/\\/g,'/').replace(/\/$/,'');
const out=process.env.CLIORA_CAPTURE_OUT ?? root+'/docs/verification/ui'; fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch();
async function mock(initialTheme){
 const names={codex:'Codex',claude_code:'Claude Code',grok:'Grok',pi:'Pi',open_code:'OpenCode'};
 const versions={codex:'0.160.0',claude_code:'2.1.287',grok:'1.0.46',pi:'1.0.0',open_code:'1.18.34'};
 const ids=Object.keys(names); let theme=initialTheme; const tool_icons={};
 const projects=[{id:'cliora',name:'栖点 · 桌面工具',path:'C:\\Projects\\cliora',preferredTool:'codex',available:true,lastOpened:1790758800,modelOverrides:{},selectedProfiles:{codex:'codex-daily'},appliedProfiles:{codex:'codex-daily'}},{id:'site',name:'个人网站',path:'C:\\Projects\\personal-site',preferredTool:'claude_code',available:true,lastOpened:1790738800,modelOverrides:{},selectedProfiles:{},appliedProfiles:{}}];
 const library=[{id:'prompt-1',kind:'prompt',title:'代码审查',body:'检查代码变更是否正确、安全、易于维护。先说明影响用户的行为，再给出具体文件和可执行的建议。优先指出会导致故障的问题。',category:'开发',projectId:null,version:1,updatedAt:1},{id:'prompt-2',kind:'prompt',title:'整理发布说明',body:'根据变更清单写一份简洁的发布说明。分成新功能、改进与修复，突出用户能直接感受到的变化。',category:'写作',projectId:null,version:1,updatedAt:1},{id:'prompt-3',kind:'prompt',title:'排查问题',body:'从可以重复出现的现象开始，提出假设并用最小实验验证。列出实际观察，不把推测当成结论。',category:'开发',projectId:'cliora',version:1,updatedAt:1},{id:'prompt-4',kind:'prompt',title:'解释一段代码',body:'用清晰的语言说明这段代码的作用、数据流与边界条件，再给出一个输入输出示例。',category:'学习',projectId:null,version:1,updatedAt:1},{id:'rule-1',kind:'rule',title:'项目协作约定',body:'保持变更小而明确。先阅读现有实现，不覆盖其他人的工作。针对实际行为验证，保留失败原因与恢复步骤。',category:'项目规则',projectId:'cliora',version:1,updatedAt:1}];
 const records=[{id:'s1',nativeId:'01992e52-1ac0-7387-a5e4-41067718dd93',toolId:'codex',title:'梳理配置继承与应用流程',cwd:projects[0].path,model:'gpt-6-astra',projectId:'cliora',startedAt:1790751600000,updatedAt:1790758800000,favorite:true,partial:false,stale:false,messageCount:8,usageCount:2},{id:'s2',nativeId:'29fbc87e',toolId:'claude_code',title:'为网站添加文章目录',cwd:projects[1].path,model:'claude-sonnet-4-6',projectId:'site',startedAt:1790748800000,updatedAt:1790751000000,favorite:false,partial:false,stale:false,messageCount:6,usageCount:1},{id:'s3',nativeId:null,toolId:'pi',title:'检查本地 API 连接',cwd:null,model:null,projectId:null,startedAt:1790718800000,updatedAt:1790718800000,favorite:false,partial:true,stale:false,messageCount:3,usageCount:0}];
 const scans=ids.map(toolId=>({toolId,scannedAt:1790758800,sourceCount:toolId==='codex'?12:4,failedCount:0,incomplete:false,detail:'本地记录已索引'}));
 const usageReport=(filter)=>{const hour=3600000,day=86400000,now=Date.now(),start=filter.fromMs??now-29*day,end=filter.toMs??now+1,step=end-start<=2*day+hour?hour:day;
  const sum=(a,b)=>({requests:a.requests+b.requests,sessions:Math.max(a.sessions,b.sessions),input:a.input+b.input,cacheRead:a.cacheRead+b.cacheRead,cacheWrite:a.cacheWrite+b.cacheWrite,output:a.output+b.output,total:a.total+b.total,cost:(a.cost??0)+(b.cost??0),unpricedTokens:a.unpricedTokens+b.unpricedTokens});
  const zero={requests:0,sessions:0,input:0,cacheRead:0,cacheWrite:0,output:0,total:0,cost:0,unpricedTokens:0};
  const make=(scale)=>{const input=Math.round(42000*scale),cacheRead=Math.round(610000*scale),cacheWrite=Math.round(9000*scale),output=Math.round(21000*scale);return {requests:Math.max(1,Math.round(18*scale)),sessions:Math.max(1,Math.round(2*scale)),input,cacheRead,cacheWrite,output,total:input+cacheRead+cacheWrite+output,cost:Math.round(scale*41)/100,unpricedTokens:Math.round(120000*scale)};};
  const timeline=[];for(let t=start;t<end;t+=step){const h=new Date(t).getHours(),d=new Date(t).getDay();const scale=t>now?0:step===hour?(h>=9&&h<=23?(1+Math.sin(h/2.2))*1.6:0):(d===0||d===6?1.5:6+Math.cos(t/day)*3);timeline.push({start:t,end:Math.min(t+step,end),totals:scale>0?make(scale):zero});}
  const totals=timeline.reduce((a,b)=>sum(a,b.totals),zero);
  const part=(share,extra={})=>({...Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,typeof v==='number'?Math.round(v*share*(k==='cost'?100:1))/(k==='cost'?100:1):v])),...extra});
  const group=(key,label,toolId,model,share,priced=true)=>({key,label,toolId,model,projectId:null,priced,totals:part(share,priced?{unpricedTokens:0}:{cost:null})});
  return {generatedAt:now,from:start,to:end,bucket:step===hour?'hour':'day',currency:'USD',totals,previous:filter.fromMs?{from:start-(end-start),to:start-(end-start)+Math.min(end,now)-start,totals:part(.82)}:null,timeline,
   byModel:[group('codex|gpt-6-astra','gpt-6-astra','codex','gpt-6-astra',.46),group('claude_code|glm-5.3','glm-5.3','claude_code','glm-5.3',.27,false),group('open_code|deepseek-v4.1-flash','deepseek-v4.1-flash','open_code','deepseek-v4.1-flash',.17,false),group('pi|devin/swe-2','devin/swe-2','pi','devin/swe-2',.07,false),group('codex|gpt-6.1-sol','gpt-6.1-sol','codex','gpt-6.1-sol',.03)],
   byTool:[group('codex','codex','codex',null,.49),group('claude_code','claude_code','claude_code',null,.27,false),group('open_code','open_code','open_code',null,.17,false),group('pi','pi','pi',null,.07,false)],
   byProject:[{...group('project:cliora','栖点 · 桌面工具',null,null,.71),projectId:'cliora'},{...group('dir:c:/projects/site','site',null,null,.21)},{...group('unknown','未归类',null,null,.08)}],
   topSessions:records.slice(0,5).map((r,i)=>({id:r.id,toolId:r.toolId,title:r.title,model:r.model,updatedAt:r.updatedAt,totals:part([.31,.22,.14,.09,.05][i])})),
   models:['deepseek-v4.1-flash','devin/swe-2','glm-5.3','gpt-6-astra','gpt-6.1-sol'],untimedRequests:0,duplicateRequests:3,partialSessions:1,staleSessions:0,mixedCurrency:false,latestEventAt:now-120000,priceSources:['codex / gpt-6-astra · OpenAI 公开价'],scans};};
 const definitions=[{id:'mcp-1',name:'filesystem',transport:'stdio',command:'npx',args:['-y','@modelcontextprotocol/server-filesystem','C:/Projects'],url:null,env:{},headers:{},version:1}];
 const skills=[{id:'skill-1',name:'code-review',description:'检查变更中的正确性、边界条件与可维护性',fileCount:3,digest:'abc',source:'local_directory',version:1}];
 const sync={configured:false,enabled:false,endpoint:null,lastSuccess:null,lastError:null,pendingChanges:0,retryAfter:null,uploaded:0,downloaded:0,conflicts:[]};
 const quotaConfig={schemaVersion:1,label:'GLM Coding Plan · 中国大陆',site:'https://open.bigmodel.cn',identity:{profileId:'codex-work',accountId:null,contextId:null,subject:'plan',subjectId:null},program:{kind:'profile_builtin',provider:'glm',templateVersion:1,profileVersion:1},parameters:{region:'cn'},targets:[{origin:'https://open.bigmodel.cn',allowPrivateNetwork:false}],enabled:true,refreshIntervalSeconds:0};
 const quotaResult={schemaVersion:1,status:'success',metrics:[{id:'five-hours',label:'五小时套餐',subject:'plan',subjectId:null,unit:{kind:'requests'},used:250,remaining:750,total:1000,sourcePercent:null,unlimited:false,window:{durationSeconds:18000,resetsAt:'2026-10-03T12:00:00Z',recovery:'rolling'},missingReason:null},{id:'week',label:'周额度',subject:'plan',subjectId:null,unit:{kind:'tokens'},used:null,remaining:null,total:null,sourcePercent:42,unlimited:false,window:{durationSeconds:604800,resetsAt:null,recovery:'rolling'},missingReason:null}],errors:[]};
 const exampleSource='async function query(ctx) {\n  const response = await ctx.http({\n    url: ctx.parameters.site + "/usage",\n    auth: { credential: ctx.credentials.api_key, prefix: "Bearer " }\n  });\n  return response.json();\n}';
 const quotaQueries=[{id:'linked-glm',version:1,generation:1,config:quotaConfig,credentials:[]},{id:'custom-usage',version:1,generation:1,config:{...quotaConfig,label:'自定义套餐脚本',program:{kind:'javascript',source:exampleSource},parameters:{site:'https://quota.example.test'},site:'https://quota.example.test',targets:[{origin:'https://quota.example.test',allowPrivateNetwork:false}]},credentials:[{name:'api_key',secretRef:'synthetic-ref',revision:1,allowedOrigins:['https://quota.example.test']}]}];
 const quotaCaches=quotaQueries.map(query=>({queryId:query.id,generation:1,success:{execution:{kind:'saved',queryId:query.id,generation:1,identity:query.config.identity},source:query.id==='linked-glm'?'profile:glm:1:1':'javascript:v1',attemptedAt:'2026-10-03T04:00:00Z',measuredAt:'2026-10-03T04:00:00Z',result:quotaResult},attemptedAt:'2026-10-03T04:00:00Z',errors:[],nextAllowedAt:0,nextAutoAt:0,failures:0,authPaused:false,refreshing:false}));
 const accounts=ids.map(toolId=>({id:'account-'+toolId,toolId,provider:toolId,version:1,label:'开发账号',state:'signed_in',identity:{subject:'fixture-'+toolId,email:'developer@example.test',plan:'订阅套餐',source:'synthetic'},context:{id:'context-'+toolId},retiredContexts:[],pendingLogin:null,detail:null,checkedAt:1790992800}));
 const pluginEntry={id:'code-review@official',name:'Code Review',source:'code-review@official',version:'1.2.0',scope:'user',enabled:true,state:'installed_load_unknown',policy:'AVAILABLE',readOnly:false,root:'C:/fixture/plugins/code-review',resources:[{kind:'agents',path:'C:/fixture/plugins/code-review/agents',ownerId:'code-review@official'}]};
 const agentEntry={id:'reviewer',name:'reviewer',description:'审查正确性、安全与边界条件',path:'C:/fixture/agents/reviewer.md',format:'markdown',content:'---\nname: reviewer\ndescription: 审查正确性、安全与边界条件\ntools: Read, Grep, Glob\nmodel: inherit\n---\n检查改动影响，引用具体证据并说明验证范围。\n',enabled:true,readOnly:false,owner:'独立定义',detail:'下一次委派读取此定义'};
 Object.assign(window,{isTauri:true,__uiCalls:[],__TAURI_INTERNALS__:{invoke:async(command,args={})=>{
  window.__uiCalls.push({command,args});
  if(command.startsWith('plugin:event|'))return 1;
  if(command==='get_bootstrap'||command==='set_theme'||command==='set_tool_icon'){if(command==='set_theme')theme=args.theme;if(command==='set_tool_icon'){if(args.dataUrl)tool_icons[args.toolId]=args.dataUrl;else delete tool_icons[args.toolId];}return {preferences:{schema_version:1,managed_tools:ids,theme,tool_icons},tools:ids.map(id=>({id,name:names[id],installation:'not_checked',configuration:'not_checked'}))};}
  if(command==='list_cli_adapters'||command==='set_registered_managed_tools')return {registered:ids.map(id=>({id,name:names[id],management:{accounts:id!=='grok',mcp:true,skills:true,agents:id!=='pi',plugins:true,projectPlugins:true},interfaceFormats:['openai_chat'],yoloAvailable:true,projectModelOverride:id==='grok',nativeConfig:{state:'available',reason:''},launch:{state:'available',reason:''},resume:{state:'available',reason:''},resources:{state:'available',reason:''},history:{state:'available',reason:''}})),managedIds:args.managedIds??ids,preservedUnknown:[]};
  if(command==='list_accounts')return window.__captureNativeOnly ? accounts.filter(account=>account.toolId!=='open_code') : accounts.map(account=>window.__captureLoginPending && account.toolId==='open_code'?{...account,state:'pending',pendingLogin:{id:'capture-attempt',operation:'login',expiresAt:1999999999}}:account);
  if(command==='discover_native_logins')return {toolId:args.toolId,checkedAt:1790992800,logins:args.toolId==='open_code'?[{provider:'openai',authKind:'oauth',state:'signed_in',identity:null,detail:'已发现本地 OAuth 登录，CLI 未提供账号身份；未在线核验。',managedAccountId:null},{provider:'anthropic',authKind:'api_key',state:'signed_in',identity:null,detail:'已配置原生 API Key；不是 OAuth 订阅账号，未在线核验。',managedAccountId:null}]:[{provider:'chatgpt',authKind:'oauth',state:'signed_in',identity:{subject:'native-user',email:'native@example.test',plan:'plus',source:'synthetic'},detail:'原生本地账号状态；未在线核验。',managedAccountId:null}]};
  if(command==='account_capabilities')return ids.map(toolId=>({toolId,provider:toolId,version:versions[toolId],browserLink:toolId==='open_code',managedLogin:toolId!=='grok',importNative:toolId!=='grok',methods:['browser','device'],reason:'使用原生登录并核验身份；截图为合成数据。',identitySource:'synthetic',refreshOwner:'native_cli',acceptance:'mock only'}));
  if(command==='list_usage_queries')return quotaQueries;
  if(command==='list_usage_cache')return quotaCaches;
  if(command==='ensure_profile_usage')return args.profileId==='codex-work'?quotaQueries[0]:null;
  if(command==='usage_presets')return [{id:'glm-cn',label:quotaConfig.label,description:'官方套餐查询，独立展示额度窗口',config:{...quotaConfig,identity:{...quotaConfig.identity,profileId:null},program:{kind:'builtin',provider:'glm',templateVersion:1}},credentials:[{name:'api_key',label:'API Key',instructions:'需要所选区域的套餐 API Key',allowedOrigins:['https://open.bigmodel.cn']}]},{id:'javascript-example',label:'自定义 JavaScript',description:'受控 HTTP 查询与结构化结果',config:{...quotaQueries[1].config,identity:{...quotaConfig.identity,profileId:null}},credentials:[]}];
  if(command==='create_usage_test')return 'capture-test';
  if(command==='test_usage_query')return {execution:{kind:'draft',executionId:args.executionId,draftRevision:args.draftRevision},result:quotaResult,error:null,elapsedMs:42,stage:'validation',preview:JSON.stringify(quotaResult,null,2),requestOrigins:[args.draft.config.site]};
  if(command==='scan_native_plugins')return {target:args.target,capability:{version:versions[args.target.toolId],sources:'plugin@marketplace',actions:['install','update','enable','disable','uninstall'],project:true,detail:'静态安装状态；重启会话后加载'},entries:[pluginEntry,{...pluginEntry,id:'required@org',name:'Organization Plugin',policy:'REQUIRED',readOnly:true}],baseline:'capture-plugins',detail:'合成插件列表，实际加载未验证'};
  if(command==='scan_native_agents')return {target:args.target,capability:{version:versions[args.target.toolId],supported:true,format:'markdown',template:agentEntry.content,detail:'下一次委派读取定义'},entries:[agentEntry,{...agentEntry,id:'plugin-reviewer',name:'plugin-reviewer',owner:'插件：code-review@official',readOnly:true}],baseline:'capture-agents',detail:'合成原生定义，插件所属定义只读'};
  if(command==='list_projects')return projects;
  if(command==='get_registered_tool_workspace'){const id=args.toolId;const format=id==='codex'||id==='grok'?'toml':'json';const file=format==='toml'?'config.toml':'settings.json';const text=format==='toml'?'# 日常开发\nmodel = "gpt-6-astra"\nmodel_reasoning_effort = "high"\n\n[projects."C:/Projects/cliora"]\ntrust_level = "trusted"':JSON.stringify({model:'claude-sonnet-4-6',permissions:{allow:['Read','Edit']}},null,2);const profile={id:id+'-daily',tool:id,name:'日常开发',version:1,revision:'r1',inheritCommon:true,files:{settings:text},suppressed:{},nativeCredentials:{},connection:null};return {probe:{selectedPath:'C:/Tools/'+id+'.cmd',installations:[{path:'C:/Tools/'+id+'.cmd',version:versions[id],status:'available',source:'npm_shim'}],nativeFiles:[{role:'settings',path:'C:/Users/local/.'+id+'/'+file,format,writable:true,sensitive:false}],nativeWrites:{state:'supported',reason:'可编辑与应用原生配置'},interfaceFormats:['openai_chat'],providerPresets:[],dependencies:[],installUrl:'https://example.com',upgradeHint:'沿用官方安装方式升级',installCommand:'npm install -g '+id,upgradeCommand:null},profiles:[profile,{...profile,id:id+'-work',name:id==='codex'?'GLM 官方套餐':'工作项目',version:1,inheritCommon:false,authentication:{kind:'api_key'},connection:id==='codex'?{providerId:'glm',interfaceFormat:'openai_responses',baseUrl:'https://open.bigmodel.cn/api/coding/paas/v4',model:'glm-5.3',secretRef:'synthetic-profile-key',authEnvVar:null}:null}],common:{tool:id,version:1,revision:'c1',files:{settings:format==='toml'?'# 所有配置共享的设置':'{}'}},binding:{profileId:profile.id,profileVersion:1},snapshots:[{role:'settings',fingerprint:'hash',error:null}],recoveryNeeded:[],customPath:null};}
  if(command==='inspect_registered_native_draft')return {model:null,providerId:null,connection:null,reasoningEffort:'high'};
  if(command==='preview_registered_native_profile')return {documents:{settings:{model:'gpt-6-astra',model_reasoning_effort:'high'}},sources:{settings:{model:'命名配置'}}};
  if(command==='read_registered_native_file_for_edit')return '# 完整磁盘原文\nmodel = "gpt-6-astra"';
  if(command==='get_launch_settings')return {selected:'power_shell',terminals:[{id:'auto',label:'系统默认',available:true},{id:'power_shell',label:'PowerShell',available:true},{id:'windows_terminal',label:'Windows Terminal',available:true}]};
  if(command==='get_tray_status')return {available:true,error:null};
  if(command==='list_library_items')return library.filter(i=>i.kind===args.kind&&(!args.search||(i.title+i.body+i.category).includes(args.search)));
  if(command==='list_mcp_definitions')return definitions;
  if(command==='list_native_mcp')return [{...definitions[0],enabled:true,protectedValues:false}];
  if(command==='list_skill_packages')return skills;
  if(command==='list_skill_installations')return [{packageId:'skill-1',toolId:'codex',scope:'global',projectPath:null,targetPath:'C:/Users/local/.codex/skills/code-review',state:'current'}];
  if(command==='list_skill_recovery_issues')return [];
  if(command==='scan_native_skills')return [{name:'code-review',path:'C:/Users/local/.codex/skills/code-review',description:'审查代码变更',managed:true}];
  if(command==='refresh_history')return scans;
  if(command==='list_history_sessions')return records.filter(i=>!args.filter.search||i.title.includes(args.filter.search));
  if(command==='get_usage_report')return usageReport(args.filter);
  if(command==='list_history_prices')return [];
  if(command==='get_history_session')return {session:records.find(i=>i.id===args.id),resumeReason:null,usage:[],messages:[{id:'m1',role:'user',timestamp:1790751600000,text:'请梳理原生配置与通用配置的继承关系，确认保存草稿和应用配置的行为。'},{id:'m2',role:'assistant',timestamp:1790751800000,text:'## 配置继承关系\n\n命名配置可以继承本工具的**通用配置**。\n\n1. 保存草稿：仅更新本机资料库。\n2. 保存并应用：合并配置并写入 CLI 原生文件。\n3. 检测到冲突：保留当前文件，等待确认。\n\n```typescript\nconst config = { ...common, ...profile };\nawait applyConfiguration(config);\n```\n\n> 已运行的会话继续使用原配置，新会话使用更新后的配置。'},{id:'m3',role:'user',timestamp:1790753600000,text:'请补充项目作用域的边界，并给出验证步骤。'}]};
  if(command==='copy_history_resume_command')return "Set-Location -LiteralPath 'C:\\Projects\\cliora'; & 'codex' "+(args.mode==='yolo'?"'--yolo' ":'')+"'resume' '01992e52-1ac0-7387-a5e4-41067718dd93'";
  if(command==='list_portable_items')return [{key:'preferences:managed',kind:'preferences',label:'外观与管理偏好',pendingFields:[]},{key:'profile:codex-daily',kind:'profile',label:'Codex · 日常开发',pendingFields:[]},{key:'library:prompt-1',kind:'library',label:'代码审查',pendingFields:[]},{key:'project:cliora',kind:'project',label:'栖点 · 桌面工具',pendingFields:['本机目录']}];
  if(command==='get_webdav_status')return sync;
  if(command==='plugin:dialog|open')return 'C:/backup.cliora';
  if(command==='preview_portable_bundle')return {previewId:'preview',pendingProjects:1,items:[{key:'profile:codex-daily',kind:'profile',toolId:'codex',label:'Codex · 日常开发',status:'conflict',pendingFields:[],localPreview:'model = "gpt-6-astra"',incomingPreview:'model = "gpt-6-sol"'},{key:'project:cliora',kind:'project',label:'栖点 · 桌面工具',status:'new',pendingFields:['项目本机目录'],localPreview:null,incomingPreview:'{"name":"栖点 · 桌面工具"}'}]};
  return null;
 }}});
}
const failures=[];
const captures=[];
for(const width of [1360,900,640])for(const theme of ['light','dark']){
 const page=await browser.newPage({viewport:{width,height:1000}});page.on('pageerror',e=>failures.push(e.message));await page.addInitScript(mock,theme);await page.goto(process.env.CLIORA_PREVIEW_URL ?? 'http://127.0.0.1:14736');await page.getByText('正在读取本机设置').waitFor({state:'hidden'});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);
 const nav=page.getByRole('navigation',{name:'页面'});
 async function capture(name){await page.mouse.move(0,0);await page.waitForTimeout(100);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);const path=`${out}/${name}-${theme}-${width}.png`;await page.screenshot({path});captures.push({name,theme,width,path});const over=await page.evaluate(()=>[...document.querySelectorAll('main,section,article,input,textarea,select,button')].filter(el=>el.getClientRects().length&&el.getBoundingClientRect().right>innerWidth+1).map(el=>({tag:el.tagName,text:el.textContent?.slice(0,60)})));if(over.length)failures.push({name,theme,width,over});console.log(path);}
 if(process.argv.includes('--records') || process.argv.includes('--sessions')){
  await nav.getByRole('button',{name:'使用记录'}).click();
  await page.getByLabel('会话列表').getByRole('button').first().waitFor();if(width>760)await page.getByRole('button',{name:'复制代码',exact:true}).waitFor();await capture('sessions');
  if(width<=760){await page.getByLabel('会话列表').getByRole('button').first().click();await page.getByRole('button',{name:'复制代码',exact:true}).waitFor();await capture('session-detail');}
  if(process.argv.includes('--sessions')){await page.getByLabel('会话正文').locator('article').nth(1).scrollIntoViewIfNeeded();await capture('session-reading');if(width<=760)await page.getByRole('button',{name:'← 返回会话列表'}).click();await page.locator('summary').filter({hasText:/^筛选/}).click();await capture('session-filters');await page.getByRole('button',{name:'自定义',exact:true}).click();const calendar=page.getByRole('dialog',{name:'自定义时间范围'});await calendar.getByRole('button',{name:/^\d{4}-\d{2}-\d{2}$/}).nth(4).click();await calendar.getByRole('button',{name:/^\d{4}-\d{2}-\d{2}$/}).nth(11).click();await capture('session-dates');await page.close();continue;}
  await page.getByRole('tab',{name:'用量',exact:true}).click();await page.getByRole('radio',{name:'近 7 天',exact:true}).click();
  await page.getByRole('region',{name:'用量概览'}).waitFor();await capture('usage');
  await page.getByRole('region',{name:'消耗最多的会话'}).scrollIntoViewIfNeeded();await capture('usage-details');await page.getByRole('radio',{name:'自定义',exact:true}).click();await capture('usage-dates');
  await page.close();continue;
 }
 await capture('home');
 await nav.getByRole('button',{name:'工具与连接'}).click();const profiles=page.getByRole('region',{name:'工具与连接'}).getByLabel('配置列表');await profiles.waitFor();await capture('tools');
 await profiles.getByRole('button',{name:'修改'}).first().click();await page.getByRole('dialog').waitFor();await capture('native-config');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 await profiles.getByRole('button',{name:'修改'}).nth(1).click();await page.getByRole('dialog').waitFor();await capture('config-form');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 const officialRow=profiles.locator('[data-profile-id="codex-work"]');await officialRow.getByText('25% 已用',{exact:true}).first().waitFor();await officialRow.scrollIntoViewIfNeeded();await capture('quota-results');
 await officialRow.locator('summary').filter({hasText:/^额度详情/}).first().click();await officialRow.getByText('最近成功：',{exact:false}).first().waitFor();await capture('quota-details');await officialRow.locator('summary').filter({hasText:/^额度详情/}).first().click();
 await officialRow.getByRole('button',{name:'额度设置'}).first().click();await page.getByRole('dialog').waitFor();await capture('quota-linked-settings');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 await officialRow.getByRole('button',{name:'额度设置'}).nth(1).click();await page.getByRole('textbox',{name:'额度查询脚本'}).waitFor();await page.getByRole('textbox',{name:'额度查询脚本'}).scrollIntoViewIfNeeded();await capture('quota-script-editor');await page.getByRole('button',{name:'测试当前草稿'}).click();await page.getByLabel('草稿测试结果').waitFor();await page.getByLabel('草稿测试结果').scrollIntoViewIfNeeded();await capture('quota-script-preview');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('tab',{name:'账号',exact:true}).click();await page.getByText('开发账号',{exact:true}).waitFor();await page.getByText('CLI 已登录',{exact:true}).waitFor();await capture('oauth-accounts');await page.getByRole('button',{name:'添加账号',exact:true}).click();await capture('oauth-add-account');
 await page.getByRole('button',{name:'删除账号',exact:true}).click();await page.getByRole('dialog').waitFor();await capture('account-delete-confirmation');await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 await page.evaluate(()=>window.__captureNativeOnly=true);await page.getByRole('tab',{name:'OpenCode',exact:true}).click();await page.getByRole('tab',{name:'账号',exact:true}).click();await page.getByText(/还没有独立账号/).waitFor();await page.getByText('CLI 已登录',{exact:true}).first().waitFor();await capture('native-cli-login');
 await page.evaluate(()=>{window.__captureNativeOnly=false;window.__captureLoginPending=true;});await page.getByRole('button',{name:'打开授权页面',exact:true}).waitFor();await capture('oauth-browser-retry');await page.evaluate(()=>window.__captureLoginPending=false);
 await page.getByRole('tab',{name:'Claude Code',exact:true}).click();
 await page.getByRole('tab',{name:'插件',exact:true}).click();await page.getByText('Code Review',{exact:true}).waitFor();await capture('native-plugins');await page.getByLabel('插件来源',{exact:true}).fill('code-review@official');await page.getByRole('checkbox').check();await capture('plugin-install');
 await page.getByLabel('搜索插件').fill('missing-plugin');await capture('plugin-search-empty');await page.getByRole('button',{name:'清除筛选'}).click();await page.getByLabel('插件状态筛选').selectOption('readonly');await capture('plugin-readonly-filter');await page.getByLabel('插件状态筛选').selectOption('all');
 await page.getByRole('tab',{name:'Agents',exact:true}).click();await page.getByText('reviewer',{exact:true}).waitFor();await capture('native-agents');await page.getByRole('listitem').filter({has:page.getByText('reviewer',{exact:true})}).getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('textbox',{name:'原生 Agent 定义',exact:true}).waitFor();await capture('agent-editor');await page.getByRole('button',{name:'关闭编辑',exact:true}).click();
 await page.getByLabel('搜索 Agent 定义').fill('missing-agent');await capture('agent-search-empty');await page.getByRole('button',{name:'清除筛选'}).click();await page.getByLabel('Agent 状态筛选').selectOption('readonly');await capture('agent-readonly-filter');await page.getByLabel('Agent 状态筛选').selectOption('all');
 await page.getByRole('tab',{name:'Grok',exact:true}).click();await page.getByRole('tab',{name:'配置',exact:true}).waitFor();if(await page.getByRole('tab',{name:'账号',exact:true}).count())throw new Error('Unsupported Grok accounts tab is visible');await capture('grok-capabilities');
 await page.getByRole('tab',{name:'Pi',exact:true}).click();await page.getByRole('tab',{name:'配置',exact:true}).waitFor();if(await page.getByRole('tab',{name:'Agents',exact:true}).count())throw new Error('Unsupported Pi agents tab is visible');await capture('pi-capabilities');
 await page.getByRole('tab',{name:'Codex',exact:true}).click();
 await page.getByRole('tab',{name:'MCP',exact:true}).click();await page.getByRole('button',{name:/filesystem/}).first().waitFor();await capture('mcp');
 await page.getByRole('tab',{name:'Skill',exact:true}).click();await page.getByRole('button',{name:/code-review/}).first().waitFor();await capture('skills');
 await nav.getByRole('button',{name:'资料库'}).click();await page.getByRole('button',{name:'代码审查',exact:true}).waitFor();await capture('library');
 await nav.getByRole('button',{name:'使用记录'}).click();await page.getByLabel('会话列表').getByRole('button').first().waitFor();if(width>760)await page.getByRole('button',{name:'在外部终端继续'}).waitFor();await capture('sessions');
 if(width<=760){await page.getByLabel('会话列表').getByRole('button').first().click();await page.getByRole('button',{name:'在外部终端继续'}).waitFor();await capture('session-detail');}
 await page.getByRole('tab',{name:'用量',exact:true}).click();await capture('usage');
 await nav.getByRole('button',{name:'设置',exact:true}).click();await capture('settings');
 await page.getByRole('tab',{name:'迁移与同步'}).click();await capture('migration');
 await page.getByRole('button',{name:'导出加密配置包',exact:true}).click();await capture('migration-export');await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'从配置包恢复',exact:true}).click();await page.getByPlaceholder('输入导出时的口令').fill('correct-password');await page.getByRole('button',{name:'选择配置包并预览'}).click();await capture('migration-import');
 await page.close();
}
await browser.close();fs.writeFileSync(`${out}/capture-ui${process.argv.includes('--sessions')?'-sessions':process.argv.includes('--records')?'-records':''}-manifest.json`,JSON.stringify({capturedAt:new Date().toISOString(),synthetic:true,captures,failures},null,2)+'\n');console.log(JSON.stringify({failures},null,2));if(failures.length)process.exitCode=1;
